const SettingsActionTypes = {
  CLEAR_POSTS_DATA: "CLEAR_POSTS_DATA",

  GET_ALL_POSTS_START: "GET_ALL_POSTS_START",
  GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
  GET_ALL_POSTS_FAILURE: "GET_ALL_POSTS_FAILURE",
};

export default SettingsActionTypes;
