const PostsActionTypes = {
  CLEAR_POSTS_DATA: "CLEAR_POSTS_DATA",

  GET_ALL_POSTS_START: "GET_ALL_POSTS_START",
  GET_BABY_POSTS_SUCCESS: "GET_BABY_POSTS_SUCCESS",
  GET_SIBLING_POSTS_SUCCESS: "GET_SIBLING_POSTS_SUCCESS",
  GET_MOTHER_POSTS_SUCCESS: "GET_MOTHER_POSTS_SUCCESS",
  GET_SPOUSE_POSTS_SUCCESS: "GET_SPOUSE_POSTS_SUCCESS",
  GET_SEX_POSTS_SUCCESS: "GET_SEX_POSTS_SUCCESS",
  GET_HEALTH_POSTS_SUCCESS: "GET_HEALTH_POSTS_SUCCESS",
  GET_ALL_POSTS_FAILURE: "GET_ALL_POSTS_FAILURE",
};

export default PostsActionTypes;
